### ISSUE TITLE
Crash on certain videos

### ISSUE THREAD

**Issue by bbaco1** [iMark21/MMYoutubeMP4Extractor#1]
hi,
there is crash that happens in MMYoutubeMP4Extractor.m

the method is
- (void)mp4FromYoutubeURL:(NSString *) url completionBlock:(void (^)(NSURL *mp4Url, NSError *error)) block

when the dictionary has one object inside, for example when i search for this youtube video
https://youtube.com/watch?v=4nT5vNb7NBk

**Comment by iMark21** [comment]
Hi @bbaco1 problem solved and updated version to 0.1.1

Thanks!
